package com.jmwl.gostudio.ui.screens.editor

import com.google.common.truth.Truth.assertThat
import org.junit.Test

/**
 * 控件声明生成器回归：ui.go 会被直接写进用户项目，
 * 命名、Go 语法、插入位置出错就意味着用户项目编译不过。
 */
class editor_widget_binding_generator_test {

    @Test
    fun `source naming for main layout`() {
        val source = editor_widget_binding_source_for("layout.xml")
        assertThat(source.file_name).isEqualTo("ui.go")
        assertThat(source.struct_name).isEqualTo("uiWidgets")
        assertThat(source.var_name).isEqualTo("ui")
        assertThat(source.bind_func).isEqualTo("bindUI")
    }

    @Test
    fun `source naming for float layout`() {
        val source = editor_widget_binding_source_for("note.xml")
        assertThat(source.file_name).isEqualTo("note_ui.go")
        assertThat(source.struct_name).isEqualTo("noteWidgets")
        assertThat(source.var_name).isEqualTo("note")
        assertThat(source.bind_func).isEqualTo("bindNote")
    }

    @Test
    fun `generated content for default template layout`() {
        val result = editor_build_widget_bindings(
            listOf("tv" to "TextView", "input" to "EditText", "btn" to "Button"),
            "layout.xml"
        )
        assertThat(result.content).isEqualTo(
            listOf(
                "// Code generated by GoStudio from layout.xml. DO NOT EDIT.",
                "",
                "package main",
                "",
                "import \"gostudio/appsdk\"",
                "",
                "// uiWidgets 是 layout.xml 中带 id 控件的句柄集合。",
                "type uiWidgets struct {",
                "\tTv    *appsdk.TextView",
                "\tInput *appsdk.EditText",
                "\tBtn   *appsdk.Button",
                "}",
                "",
                "var ui uiWidgets",
                "",
                "// bindUI 绑定 layout.xml 的控件，请在 appsdk.Start() 之后调用一次。",
                "func bindUI(app *appsdk.App) {",
                "\tui.Tv = app.TextView(\"tv\")",
                "\tui.Input = app.EditText(\"input\")",
                "\tui.Btn = app.Button(\"btn\")",
                "}"
            ).joinToString("\n") + "\n"
        )
    }

    @Test
    fun `id sanitized into go field name`() {
        val result = editor_build_widget_bindings(
            listOf("my-btn" to "TextView", "1st" to "Button", "a_1" to "Switch"),
            "layout.xml"
        )
        val fields = result.bindings.map { it.field }
        assertThat(fields).containsExactly("MyBtn", "Widget1st", "A1").inOrder()
    }

    @Test
    fun `duplicate sanitized fields get suffix`() {
        val result = editor_build_widget_bindings(
            listOf("tv" to "TextView", "Tv" to "Button"),
            "layout.xml"
        )
        assertThat(result.bindings.map { it.field }).containsExactly("Tv", "Tv2").inOrder()
    }

    @Test
    fun `empty tags rejected`() {
        val caught = runCatching {
            editor_build_widget_bindings(emptyList(), "layout.xml")
        }.exceptionOrNull()
        assertThat(caught).isInstanceOf(IllegalArgumentException::class.java)
        assertThat(caught).hasMessageThat().contains("没有带 id")
    }

    @Test
    fun `bind call inserted after start with actual var name`() {
        val entry = """
            package main

            import "gostudio/appsdk"

            func main() {
            	myapp := appsdk.Start()
            	myapp.Run()
            }
        """.trimIndent().replace("    ", "\t")
        val insertion = editor_insert_bind_call(entry, "bindUI")
        assertThat(insertion.status).isEqualTo(editor_bind_call_status.INSERTED)
        assertThat(insertion.content).contains("myapp := appsdk.Start()\n\tbindUI(myapp)")
    }

    @Test
    fun `bind call not duplicated`() {
        val entry = """
            func main() {
            	app := appsdk.Start()
            	bindUI(app)
            	app.Run()
            }
        """.trimIndent().replace("    ", "\t")
        val insertion = editor_insert_bind_call(entry, "bindUI")
        assertThat(insertion.status).isEqualTo(editor_bind_call_status.ALREADY_PRESENT)
        assertThat(insertion.content).isEqualTo(entry)
    }

    @Test
    fun `anchor missing when start absent`() {
        val insertion = editor_insert_bind_call("func main() {\n}\n", "bindUI")
        assertThat(insertion.status).isEqualTo(editor_bind_call_status.ANCHOR_MISSING)
    }

    @Test
    fun `duplicate ids rejected when parsing`() {
        val xml = """
            <LinearLayout>
                <TextView id="tv"/>
                <Button id="tv"/>
            </LinearLayout>
        """.trimIndent()
        val error = editor_parse_widget_binding_tags(xml).exceptionOrNull()
        assertThat(error).isInstanceOf(IllegalArgumentException::class.java)
        assertThat(error).hasMessageThat().contains("tv")
    }
}
