package com.jmwl.gostudio.toolchain

import android.content.Context
import android.net.ConnectivityManager
import android.net.LinkProperties
import java.io.File
import java.util.Locale

/**
 * 把 Android 系统当前生效的 DNS 写进 rootfs 的 /etc/resolv.conf。
 *
 * rootfs_patcher 的 ensure_dns 只会写一组写死的公共 DNS（1.1.1.1/8.8.8.8 等），
 * 在国内运营商网络下这些地址的 UDP 53 常被拦截，沙盒里 musl 解析全部超时，
 * 表现为 apk 报 "DNS: transient error"。系统自身在用的 DNS（ConnectivityManager
 * 提供）天然可达——每次 proot 执行前刷新一次，网络切换后也能自动跟上。
 *
 * 兜底保留 223.5.5.5：系统 DNS 短暂失效时 musl 仍可解析。
 */
object sandbox_dns {

    fun refresh(context: Context) {
        try {
            val rootfs = toolchain_runtime_provider.paths().rootfs_dir
            val etc_dir = File(rootfs, "etc")
            if (!etc_dir.isDirectory) return

            val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager ?: return
            val network = cm.activeNetwork ?: return
            val props: LinkProperties = cm.getLinkProperties(network) ?: return
            // 过滤带 scope 的 IPv6 链路本地地址（fe80::1%wlan0 这类 musl 解析不了）
            val servers = props.dnsServers
                .mapNotNull { it.hostAddress }
                .filter { it.isNotBlank() && !it.contains('%') && !it.startsWith("fe80", ignoreCase = true) }
                .map { it.lowercase(Locale.US) }
                .distinct()
            if (servers.isEmpty()) return

            val resolv_conf = File(etc_dir, "resolv.conf")
            resolv_conf.writeText(
                buildString {
                    appendLine("# Generated by GoStudio (system DNS via ConnectivityManager)")
                    props.domains?.takeIf { it.isNotBlank() }?.let { appendLine("search $it") }
                    servers.take(3).forEach { appendLine("nameserver $it") }
                    appendLine("nameserver 223.5.5.5")
                }
            )
        } catch (_: Exception) {
            // DNS 刷新失败不阻断命令执行，rootfs_patcher 的静态 DNS 兜底仍在
        }
    }
}
